version: '3'
services:
  db:
    image: postgres:14.5-alpine
    env_file: .env
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    env_file: .env
    ports:
      - '4000:80'
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - db
volumes:
  pgdata:
  pgadmin-data:
