version: '3'
services:
  app:
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
      target: production
    env_file: .env
    command: npm start
    ports:
      - '3000:3000'
    depends_on:
      - db
  db:
    image: postgres:14.5-alpine
    env_file: .env
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
