version: '3'
services:
  app:
    build:
      context: ../
      dockerfile: backend/docker/services/app/Dockerfile
    environment:
      NODE_ENV: production
      DB_HOST: db
      DB_PORT: 5432
    command: npm start
    ports:
      - "80:3000"
    depends_on:
      - db
  db:
    build:
      context: ../
      dockerfile: backend/docker/services/db/Dockerfile
    environment:
      DB_PORT: 5432
    ports:
      - ${DB_PORT}:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:


