export const GAME_HEIGHT = 800;
export const GAME_WIDTH = 1024;
export const PLAYER_HEIGHT = 48;
export const PLAYER_WIDTH = 48;
export const TOP_PADDING = 10;
export const BOTTOM_PADDING = 10;
export const LEFT_PADDING = 10;
export const RIGHT_PADDING = 10;
export const ENEMY_WIDTH = 48;
export const ENEMY_HEIGHT = 48;
export const ENEMY_GAP = 3;
export const ENEMY_FIRE_RATE = 1500; // раз в 1,5 секунды
export const PLAYER_FIRE_RATE = 500; // раз в 0,5 секунды
export const ENEMY_BULLET_HEIGHT = 24;
export const ENEMY_BULLET_WIDTH = 9;
export const PLAYER_BULLET_HEIGHT = 24;
export const PLAYER_BULLET_WIDTH = 9;
export const BULLET_OFFSET_X = 18;
export const BULLET_OFFSET_Y = 12;
export const BASE_SCORE = 100;
export const STAR_COUNT = 150;
export const STAR_COLORS = ['red', 'green', 'white', 'yellow'];
